# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-20 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=datetime.datetime(2018, 8, 20, 21, 33, 40, 983818), upload_to='teacher/%Y%m%d', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
