# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-27 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180823_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseResourse',
            new_name='CourseResource',
        ),
    ]
