# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-27 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180827_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='访问地址'),
        ),
    ]
