# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-14 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(null=True, verbose_name='生日'),
        ),
    ]
